---
title: "Activations"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r, include = FALSE}
rm(list=ls())
library(plotfunctions)
source("C:/Users/Sanne/Dropbox/MasterProject/Modelling/OriginalExperimentRun.R")
```

```{r, echo = FALSE}
listY <- list()
FirstRun <- data.frame(Cues = Cues2, Outcomes = Outcome050, stringsAsFactors = FALSE)
train.FR <- createTrainingData(FirstRun, random = F)
wm.FR <- EDLearning(train.FR, progress = F, etaNeg = FALSE)
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.FR,i))
  df$Trial <- i
  listX<-list.append(listX, df)
}
listY <- bind_rows(listX)

SecondRun <- data.frame(Cues = Cues1, Outcomes = Outcome000, stringsAsFactors = FALSE)
train.SR <- createTrainingData(SecondRun, random = F)
wm.SR <- EDLearning(train.SR, progress = F, etaNeg = FALSE, wm = wm.FR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.SR,i))
  df$Trial <- i+16
  listX<-list.append(listX, df)
}
listZ<- bind_rows(listX)
listY<- rbind(listY, listZ)

ThirdRun <- data.frame(Cues = Cues3, Outcomes = Outcome100, stringsAsFactors = FALSE)
train.TR <- createTrainingData(ThirdRun, random = F)
wm.TR <- EDLearning(train.TR, progress = F, etaNeg = FALSE, wm = wm.SR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.TR,i))
  df$Trial <- i+32
  listX<-list.append(listX, df)
}
listA<- bind_rows(listX)
listY<- rbind(listY, listA)

word <- c("shrimp", "yoghurt", "bananas", "wheat", "corn", "blueberries", "strawberries", "bran", "chicken", "walnuts", "horseradish", "cheese", "peanuts", "cabbage", "mustard", "peaches", "lobster", "pork", "env")
exactWord <- c("shrimp","yoghurt", "bananas", "wheat", "corn", "blueberries", "strawberries", "bran", "chicken", "walnuts", "horseradish", "cheese", "peanuts", "cabbage", "mustard", "peaches", "lobster", "pork", "env")
exactWords <- data.frame(Word = word, exactWord = exactWord, stringsAsFactors = FALSE)
getexactwords <- exactWords$exactWord
names(getexactwords) <- exactWords$Word
listY$Word <- NA
for(i in 1:nrow(listY)){
  listY[i,]$Word <- getexactwords[gsub("...[0-9]+", "",row.names(listY[i,]))]
}

listY2 <- list()
FirstRun <- data.frame(Cues = Cues2, Outcomes = Outcome050, stringsAsFactors = FALSE)
train.FR <- createTrainingData(FirstRun, random = F)
wm.FR <- EDLearning(train.FR, progress = F, etaNeg = TRUE)
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.FR,i))
  df$Trial <- i
  listX<-list.append(listX, df)
}
#listY<- listX
listY2 <- bind_rows(listX)

SecondRun <- data.frame(Cues = Cues1, Outcomes = Outcome000, stringsAsFactors = FALSE)
train.SR <- createTrainingData(SecondRun, random = F)
wm.SR <- EDLearning(train.SR, progress = F, etaNeg = TRUE, wm = wm.FR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.SR,i))
  df$Trial <- i+16
  listX<-list.append(listX, df)
}
listZ<- bind_rows(listX)
listY2<- rbind(listY2, listZ)

ThirdRun <- data.frame(Cues = Cues3, Outcomes = Outcome100, stringsAsFactors = FALSE)
train.TR <- createTrainingData(ThirdRun, random = F)
wm.TR <- EDLearning(train.TR, progress = F, etaNeg = TRUE, wm = wm.SR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.TR,i))
  df$Trial <- i+32
  listX<-list.append(listX, df)
}
listA<- bind_rows(listX)
listY2<- rbind(listY2, listA)

listY2$Word <- NA
for(i in 1:nrow(listY)){
  listY2[i,]$Word <- getexactwords[gsub("...[0-9]+", "",row.names(listY2[i,]))]

}

```


PAPER
```{r, echo = FALSE}
par(mfrow = c(1,1))
par(las = 1)
emptyPlot(c(1,60),c(-.08,.09), xmark = c(1,8,16,24,32,40,48), ymark = c( -.05, .00, .05), bty='n', main = "Rescorla-Wagner", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY$Allergic)[listY$Word == "bran"]-(listY$Not)[listY$Word=="bran"], type = "l", col = "blue", lwd = 2)
text(51,0.038, labels = "bran", col = "blue" )
points(c(1:48), (listY$Allergic)[listY$Word == "env"]-(listY$Not)[listY$Word=="env"], type = "l", col = "black", lwd = 2)
text(51,0.01, labels = "env", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"]-(listY$Not)[listY$Word=="yoghurt"], type = "l", col = "cyan", lwd = 2)
text(51,-0.017, labels = "yoghurt", col = "cyan" )
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"]-(listY$Not)[listY$Word=="cabbage"], type = "l", col = "green", lwd = 2)
text(51,-0.037, labels = "cabbage", col = "green" )
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]-(listY$Not)[listY$Word=="shrimp"]), type = "l", col = "grey")
text(51,-0.005, labels = "shrimp", col = "grey")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]-(listY$Not)[listY$Word=="strawberries"]), type = "l", col = "grey")
text(51,-0.01, labels = "strawb.", col = "grey")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]-(listY$Not)[listY$Word=="peanuts"]), type = "l", col = "grey")
text(51,0.002, labels = "peanuts", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]-(listY$Not)[listY$Word=="bananas"]), type = "l", col = "grey")
text(51,0.018, labels = "bananas", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]-(listY$Not)[listY$Word=="chicken"]), type = "l", col = "grey")
text(51,0.07, labels = "chicken", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]-(listY$Not)[listY$Word=="mustard"]), type = "l", col = "grey")
text(51,-0.06, labels = "mustard", col = "grey" )
par(xpd = FALSE) 
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)


emptyPlot(c(1,60),c(-.08,.09), xmark = c(1,8,16,24,32,40,48), ymark = c(-.05, .00, .05), bty='n', main = "Van Hamme-Wasserman", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"]-(listY2$Not)[listY2$Word=="bran"], type = "l", col = "blue", lwd = 2)
text(51,0.08, labels = "bran", col = "blue" )
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"]-(listY2$Not)[listY2$Word=="env"], type = "l", col = "black", lwd = 2)
text(51,0.01, labels = "env", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"]-(listY2$Not)[listY2$Word=="yoghurt"], type = "l", col = "cyan", lwd = 2)
text(51,-0.017, labels = "yoghurt", col = "cyan" )
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"]-(listY2$Not)[listY2$Word=="cabbage"], type = "l", col = "green", lwd = 2)
text(51,-0.06, labels = "cabbage", col = "green" )
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]-(listY2$Not)[listY2$Word=="shrimp"]), type = "l", col = "grey")
text(51,-0.005, labels = "shrimp", col = "grey")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]-(listY2$Not)[listY2$Word=="strawberries"]), type = "l", col = "grey")
text(51,-0.01, labels = "strawb.", col = "grey")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]-(listY2$Not)[listY2$Word=="peanuts"]), type = "l", col = "grey")
text(51,0.002, labels = "peanuts", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]-(listY2$Not)[listY2$Word=="bananas"]), type = "l", col = "grey")
text(51,0.018, labels = "bananas", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]-(listY2$Not)[listY2$Word=="chicken"]), type = "l", col = "grey")
text(51,0.088, labels = "chicken", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]-(listY2$Not)[listY2$Word=="mustard"]), type = "l", col = "grey")
text(51,-0.078, labels = "mustard", col = "grey" )
par(xpd = FALSE) 
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)
```

#COLOUR
```{r, echo = FALSE}
par(mfrow = c(1,1))
par(las = 1)
emptyPlot(c(1,60),c(-.08,.09), xmark = c(1,8,16,24,32,40,48), ymark = c( -.05, .00, .05), bty='n', main = "Rescorla-Wagner", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY$Allergic)[listY$Word == "bran"]-(listY$Not)[listY$Word=="bran"], type = "l", col = "blue")
text(51,0.038, labels = "bran", col = "blue" )
points(c(1:48), (listY$Allergic)[listY$Word == "env"]-(listY$Not)[listY$Word=="env"], type = "l", col = "black")
text(51,0.01, labels = "env", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"]-(listY$Not)[listY$Word=="yoghurt"], type = "l", col = "cyan")
text(51,-0.017, labels = "yoghurt", col = "cyan" )
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"]-(listY$Not)[listY$Word=="cabbage"], type = "l", col = "green")
text(51,-0.037, labels = "cabbage", col = "green" )
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]-(listY$Not)[listY$Word=="shrimp"]), type = "l", col = "pink")
text(51,-0.005, labels = "shrimp", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]-(listY$Not)[listY$Word=="strawberries"]), type = "l", col = "red")
text(51,-0.01, labels = "strawb.", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]-(listY$Not)[listY$Word=="peanuts"]), type = "l", col = "brown")
text(51,0.002, labels = "peanuts", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]-(listY$Not)[listY$Word=="bananas"]), type = "l", col = "yellow")
text(51,0.018, labels = "bananas", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]-(listY$Not)[listY$Word=="chicken"]), type = "l", col = "orange")
text(51,0.07, labels = "chicken", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]-(listY$Not)[listY$Word=="mustard"]), type = "l", col = "grey")
text(51,-0.06, labels = "mustard", col = "grey" )
par(xpd = FALSE) 
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)


emptyPlot(c(1,60),c(-.08,.09), xmark = c(1,8,16,24,32,40,48), ymark = c(-.05, .00, .05), bty='n', main = "Van Hamme-Wasserman", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"]-(listY2$Not)[listY2$Word=="bran"], type = "l", col = "blue")
text(51,0.08, labels = "bran", col = "blue" )
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"]-(listY2$Not)[listY2$Word=="env"], type = "l", col = "black")
text(51,0.01, labels = "env", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"]-(listY2$Not)[listY2$Word=="yoghurt"], type = "l", col = "cyan")
text(51,-0.017, labels = "yoghurt", col = "cyan" )
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"]-(listY2$Not)[listY2$Word=="cabbage"], type = "l", col = "green")
text(51,-0.06, labels = "cabbage", col = "green" )
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]-(listY2$Not)[listY2$Word=="shrimp"]), type = "l", col = "pink")
text(51,-0.005, labels = "shrimp", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]-(listY2$Not)[listY2$Word=="strawberries"]), type = "l", col = "red")
text(51,-0.01, labels = "strawb.", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]-(listY2$Not)[listY2$Word=="peanuts"]), type = "l", col = "brown")
text(51,0.002, labels = "peanuts", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]-(listY2$Not)[listY2$Word=="bananas"]), type = "l", col = "yellow")
text(51,0.018, labels = "bananas", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]-(listY2$Not)[listY2$Word=="chicken"]), type = "l", col = "orange")
text(51,0.088, labels = "chicken", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]-(listY2$Not)[listY2$Word=="mustard"]), type = "l", col = "grey")
text(51,-0.078, labels = "mustard", col = "grey" )
par(xpd = FALSE) 
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)
```


```{r, echo = FALSE}
par(las=1)
emptyPlot(c(1,60),c(-.03,.08), xmark = c(1,16,32,48), bty='n', main = "Rescorla-Wagner \n Absent cues are not updated", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY$Allergic)[listY$Word == "bran"], type = "l", col = "blue", lty = 2, lwd = 2)
text(51,0.055, labels = "bran", col = "blue", cex = 1.2)
points(c(1:48), (listY$Allergic)[listY$Word == "env"], type = "l", col = "black", lty = 1, lwd = 2)
text(24,0.08, labels = "env", col = "black", cex = 1.2)
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"], type = "l", col = "cyan", lty =4, lwd =2)
text(51,0.07, labels = "yoghurt", col = "cyan" , cex = 1.2)
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"], type = "l", col = "green", lty =5 ,lwd = 2)
text(51,0.018, labels = "cabbage", col = "green" , cex = 1.2)
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]), type = "l", col = "gray")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=FALSE)
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)

emptyPlot(c(1,60),c(-.03,.08), xmark = c(1,16,32,48), bty='n', main = "Van Hamme-Wasserman \n Absent cues are updated", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"], type = "l", col = "blue", lty = 2, lwd = 2)
text(33,-0.01, labels = "bran", col = "blue" , cex = 1.2)
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"], type = "l", col = "black", lty = 1, lwd = 2)
text(24,0.08, labels = "env", col = "black", cex = 1.2)
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"], type = "l", col = "cyan", lty =4, lwd = 2)
text(48,-0.02, labels = "yoghurt", col = "cyan", cex = 1.2 )
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"], type = "l", col = "green", lty =5, lwd = 2)
text(20,-0.02, labels = "cabbage", col = "green", cex = 1.2 )
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]), type = "l", col = "gray")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]), type = "l", col = "grey")
par(xpd=FALSE)
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)



```

```{r, echo = FALSE}
par(las=1)
emptyPlot(c(1,60),c(-.03,.08), xmark = c(1,16,32,48), bty='n', main = "Rescorla-Wagner \n Absent cues are not updated", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY$Not)[listY$Word == "bran"], type = "l", col = "blue", lty = 2, lwd = 2)
text(51.5,0.018, labels = "bran", col = "blue", cex = 1.2)
points(c(1:48), (listY$Not)[listY$Word == "env"], type = "l", col = "black", lty = 1, lwd = 2)
text(24,0.08, labels = "env", col = "black", cex = 1.2)
points(c(1:48), (listY$Not)[listY$Word == "yoghurt"], type = "l", col = "cyan", lty =4, lwd =2)
text(51,0.07, labels = "yoghurt", col = "cyan" , cex = 1.2)
points(c(1:48), (listY$Not)[listY$Word == "cabbage"], type = "l", col = "green", lty =5 ,lwd = 2)
text(51,0.055, labels = "cabbage", col = "green" , cex = 1.2)
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "shrimp"]), type = "l", col = "gray")
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "strawberries"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "peanuts"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "bananas"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "chicken"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=FALSE)
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)

emptyPlot(c(1,60),c(-.03,.08), xmark = c(1,16,32,48), bty='n', main = "Van Hamme-Wasserman \n Absent cues are updated", xlab="", ylab = "Connection weights")
mtext("Block 1", side = 1, at = 8, line = 2.5)
mtext("Block 2", side = 1, at = 24, line = 2.5)
mtext("Block 3", side = 1, at = 40, line = 2.5)
points(c(1:48), (listY2$Not)[listY2$Word == "bran"], type = "l", col = "blue", lty = 2, lwd = 2)
text(20,-0.02, labels = "bran", col = "blue" , cex = 1.2)
points(c(1:48), (listY2$Not)[listY2$Word == "env"], type = "l", col = "black", lty = 1, lwd = 2)
text(24,0.08, labels = "env", col = "black", cex = 1.2)
points(c(1:48), (listY2$Not)[listY2$Word == "yoghurt"], type = "l", col = "cyan", lty =4, lwd = 2)
text(48,-0.02, labels = "yoghurt", col = "cyan", cex = 1.2 )
points(c(1:48), (listY2$Not)[listY2$Word == "cabbage"], type = "l", col = "green", lty =5, lwd = 2)
text(33,-0.01, labels = "cabbage", col = "green", cex = 1.2 )
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "shrimp"]), type = "l", col = "gray")
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "strawberries"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "peanuts"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "bananas"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "chicken"]), type = "l", col = "grey")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "mustard"]), type = "l", col = "grey")
par(xpd=FALSE)
abline(v=16, col = "grey", lty = 2)
abline(v=32, col = "grey", lty = 2)


```



```{r, echo = FALSE}
par(las=1)
emptyPlot(c(1,60),c(-.03,.08), xmark = c(1:48), bty='n', main = "Weights to Allergic, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

par(las=1)
emptyPlot(c(1,60),c(-.03,.08), xmark = c(1:48), bty='n', main = "Weights to Not, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Not)[listY$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY$Not)[listY$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY$Not)[listY$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Not)[listY$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Not)[listY$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Not)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

emptyPlot(c(1,60),c(-.08,.09), xmark = c(1:48), bty='n', main = "Weights to Allergic minus not, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"]-(listY$Not)[listY$Word=="bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"]-(listY$Not)[listY$Word=="env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"]-(listY$Not)[listY$Word=="yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"]-(listY$Not)[listY$Word=="cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]-(listY$Not)[listY$Word=="shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]-(listY$Not)[listY$Word=="strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]-(listY$Not)[listY$Word=="peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]-(listY$Not)[listY$Word=="bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]-(listY$Not)[listY$Word=="chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]-(listY$Not)[listY$Word=="mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

```

### VHW

```{r, echo = FALSE}
listY2 <- list()
FirstRun <- data.frame(Cues = Cues2, Outcomes = Outcome050, stringsAsFactors = FALSE)
train.FR <- createTrainingData(FirstRun, random = F)
wm.FR <- EDLearning(train.FR, progress = F, etaNeg = TRUE)
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.FR,i))
  df$Trial <- i
  listX<-list.append(listX, df)
}
#listY<- listX
listY2 <- bind_rows(listX)

SecondRun <- data.frame(Cues = Cues1, Outcomes = Outcome000, stringsAsFactors = FALSE)
train.SR <- createTrainingData(SecondRun, random = F)
wm.SR <- EDLearning(train.SR, progress = F, etaNeg = TRUE, wm = wm.FR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.SR,i))
  df$Trial <- i+16
  listX<-list.append(listX, df)
}
listZ<- bind_rows(listX)
listY2<- rbind(listY2, listZ)

ThirdRun <- data.frame(Cues = Cues3, Outcomes = Outcome100, stringsAsFactors = FALSE)
train.TR <- createTrainingData(ThirdRun, random = F)
wm.TR <- EDLearning(train.TR, progress = F, etaNeg = TRUE, wm = wm.SR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.TR,i))
  df$Trial <- i+32
  listX<-list.append(listX, df)
}
listA<- bind_rows(listX)
listY2<- rbind(listY2, listA)

listY2$Word <- NA
for(i in 1:nrow(listY)){
  listY2[i,]$Word <- getexactwords[gsub("...[0-9]+", "",row.names(listY2[i,]))]

}


```

```{r, echo = FALSE}
par(las=1)
emptyPlot(c(1,60),c(-0.15,0.15), xmark = c(1:48), bty='n', main = "Weights to Allergic, VHW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)


par(las=1)
emptyPlot(c(1,60),c(-0.15,0.15), xmark = c(1:48), bty='n', main = "Weights to Not, VHW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY2$Not)[listY2$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY2$Not)[listY2$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY2$Not)[listY2$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY2$Not)[listY2$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Not)[listY2$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Not)[listY2$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)



emptyPlot(c(1,60),c(-0.08,0.09), xmark = c(1:48), bty='n', main = "Weights to Allergic minus not, VHW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"]-(listY2$Not)[listY2$Word=="bran"], type = "l", col = "blue")
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"]-(listY2$Not)[listY2$Word=="env"], type = "l", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"]-(listY2$Not)[listY2$Word=="yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"]-(listY2$Not)[listY2$Word=="cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]-(listY2$Not)[listY2$Word=="shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]-(listY2$Not)[listY2$Word=="strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]-(listY2$Not)[listY2$Word=="peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]-(listY2$Not)[listY2$Word=="bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]-(listY2$Not)[listY2$Word=="chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]-(listY2$Not)[listY2$Word=="mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

```

The order of stimuli presented was 2,1,3, which is XAB: (yoghurt, bran, cabbage), (shrimp, strawberries, peanuts), (bananas, chicken, mustard)

### Comparing both on a weights to allergic level
```{r, echo = FALSE}
par(mfrow = c(1,2))
par(las = 1)
emptyPlot(c(1,55),c(-0.15,0.15), xmark = c(1,8,16,24,32,40,48), bty='n', main = "Weights to Allergic, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
#legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

emptyPlot(c(1,55),c(-0.15,0.15), xmark = c(1,8,16,24,32,40,48), bty='n', main = "Weights to Allergic, VHW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
#legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)
```


### Comparing both on a weights to allergic minus weights to not level
```{r, echo = FALSE}
par(mfrow = c(1,2), las = 1)
emptyPlot(c(1,60),c(-.08,.09), xmark = c(1,8,16,24,32,40,48), bty='n', main = "Weights to Allergic minus not, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"]-(listY$Not)[listY$Word=="bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"]-(listY$Not)[listY$Word=="env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"]-(listY$Not)[listY$Word=="yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"]-(listY$Not)[listY$Word=="cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]-(listY$Not)[listY$Word=="shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]-(listY$Not)[listY$Word=="strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]-(listY$Not)[listY$Word=="peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]-(listY$Not)[listY$Word=="bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]-(listY$Not)[listY$Word=="chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]-(listY$Not)[listY$Word=="mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)


emptyPlot(c(1,60),c(-0.08,0.09), xmark = c(1,8,16,24,32,40,48), bty='n', main = "Weights to Allergic minus not, VHW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY2$Allergic)[listY2$Word == "bran"]-(listY2$Not)[listY2$Word=="bran"], type = "l", col = "blue")
points(c(1:48), (listY2$Allergic)[listY2$Word == "env"]-(listY2$Not)[listY2$Word=="env"], type = "l", col = "black")
points(c(1:48), (listY2$Allergic)[listY2$Word == "yoghurt"]-(listY2$Not)[listY2$Word=="yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY2$Allergic)[listY2$Word == "cabbage"]-(listY2$Not)[listY2$Word=="cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "shrimp"]-(listY2$Not)[listY2$Word=="shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "strawberries"]-(listY2$Not)[listY2$Word=="strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY2$Allergic)[listY2$Word == "peanuts"]-(listY2$Not)[listY2$Word=="peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "bananas"]-(listY2$Not)[listY2$Word=="bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "chicken"]-(listY2$Not)[listY2$Word=="chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY2$Allergic)[listY2$Word == "mustard"]-(listY2$Not)[listY2$Word=="mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)
```