---
title: "Fixing VHW"
output:
  html_document:
    df_print: paged
---

```{r, Loading in packages, include = FALSE}
rm(list=ls())
library(ndl)
library(plotfunctions)
library(data.table)
library(edl)
library(stringr)
library(rlist)
library(dplyr)
library(roperators)
source("C:/Users/Sanne/Dropbox/MasterProject/Modelling/VanHammeWassermanFunctions.R") #loading in the file for the functions created
```

```{r, all cues and outcomes}
Cue <- c("A_X", "B_X", "B_X", "A_X", "A_X", "B_X", "A_X", "B_X", "B_X", "A_X", "B_X", "A_X", "A_X", "B_X", "A_X", "B_X")
Cue <- paste("env", Cue, sep = "_")
Cues1 <- FillInCues("strawberries", "peanuts", "shrimp", Cue)
Cues2 <- FillInCues("bran", "cabbage", "yoghurt", Cue)
Cues3 <- FillInCues("chicken", "mustard", "bananas", Cue)
Cues4 <- FillInCues("walnuts", "peaches", "wheat", Cue)
Cues5 <- FillInCues("horseradish", "lobster", "corn", Cue)
Cues6 <- FillInCues("cheese", "pork", "blueberries", Cue)

###
Outcome000 <- c("Allergic", "Not", "Allergic", "Not", "Not", "Allergic", "Allergic", "Not", "Allergic", "Not", "Not", "Allergic", "Not", "Allergic", "Allergic", "Not")
Outcome050 <- c("Allergic", "Not", "Allergic", "Allergic", "Not", "Not", "Allergic", "Not", "Allergic", "Allergic", "Not", "Allergic", "Not", "Not", "Allergic", "Not")
Outcome100 <- c("Allergic", "Not", "Not", "Allergic", "Allergic", "Not", "Allergic", "Not", "Not", "Allergic", "Not", "Allergic", "Allergic", "Not", "Allergic", "Not")
```


### RW learning split groups
```{r, RW}
#Group 1
#split in 3,4
Group1_1 <- bind_rows(ParticipantRun(Cues2, Cues1, Cues3, Outcome050, Outcome000, Outcome100, 3))
Group1_2 <- bind_rows(ParticipantRun(Cues5, Cues6, Cues4, Outcome050, Outcome100, Outcome000, 4))
#now I want to make one big 
Group1 <- rbind(Group1_1, Group1_2)

#Group2, split 4,4
Group2_1 <- bind_rows(ParticipantRun(Cues1, Cues3, Cues2, Outcome000, Outcome100, Outcome050, 4))
Group2_2 <- bind_rows(ParticipantRun(Cues4, Cues5, Cues6, Outcome000, Outcome050, Outcome100, 4))
Group2 <- rbind(Group2_1, Group2_2)

#Group3, split 3,3
Group3_1 <- bind_rows(ParticipantRun(Cues3, Cues2, Cues1, Outcome100, Outcome050, Outcome000, 3))
Group3_2 <- bind_rows(ParticipantRun(Cues6, Cues4, Cues5, Outcome100, Outcome000, Outcome050, 3))
Group3 <- rbind(Group3_1, Group3_2)

#Group4, split 4,4
Group4_1 <- bind_rows(ParticipantRun(Cues5, Cues6, Cues4, Outcome050, Outcome100, Outcome000, 4))
Group4_2 <- bind_rows(ParticipantRun(Cues2, Cues1, Cues3, Outcome050, Outcome000, Outcome100, 4))
Group4 <- rbind(Group4_1, Group4_2)

#Group5, split 5,5
Group5_1 <- bind_rows(ParticipantRun(Cues4, Cues5, Cues6, Outcome000, Outcome050, Outcome100, 5))
Group5_2 <- bind_rows(ParticipantRun(Cues1, Cues3, Cues2, Outcome000, Outcome100, Outcome050, 5))
Group5 <- rbind(Group5_1, Group5_2)

#Group6, split 5,4
Group6_1 <- bind_rows(ParticipantRun(Cues6, Cues4, Cues5, Outcome100, Outcome000, Outcome050, 4))
Group6_2 <- bind_rows(ParticipantRun(Cues3, Cues2, Cues1, Outcome100, Outcome050, Outcome000, 4))
Group6 <- rbind(Group6_1, Group6_2)

All <- rbind(Group1, Group2, Group3, Group4, Group5, Group6)
All$wordType <- NA
for(i in 1:nrow(All)){
  All[i,]$wordType <- getwords[gsub("...[0-9]+", "",row.names(All[i,]))]
}
aggAll <- aggregate(All$Allergic, list(All$Cond, All$wordType), mean)
aggAll
aggAllNot <- aggregate(All$Not, list(All$Cond, All$wordType), mean)
aggAllNot
``` 



```{r}
par(mfrow = c(1,2))
A <- c((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "A"], (aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "A"], (aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "A"])
B <- c((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "B"], (aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "B"], (aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "B"])
X <- c((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "X"], (aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "X"], (aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "X"])

emptyPlot(c(-5,105),c(-0.02,0.05), xmark = c(0,50,100), bty='n', main = "Weights allergic", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0,legend =c("A", "B", "X"), pch = c(0,16,15))

A<- c(((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "A"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome000" & aggAllNot$Group.2 == "A"])), ((aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "A"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome050" & aggAllNot$Group.2 == "A"])), ((aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "A"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome100" & aggAllNot$Group.2 == "A"])))
B<- c(((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "B"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome000" & aggAllNot$Group.2 == "B"])), ((aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "B"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome050" & aggAllNot$Group.2 == "B"])), ((aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "B"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome100" & aggAllNot$Group.2 == "B"])))
X<- c(((aggAll$x)[aggAll$Group.1 == "Outcome000" & aggAll$Group.2 == "X"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome000" & aggAllNot$Group.2 == "X"])), ((aggAll$x)[aggAll$Group.1 == "Outcome050" & aggAll$Group.2 == "X"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome050" & aggAllNot$Group.2 == "X"])), ((aggAll$x)[aggAll$Group.1 == "Outcome100" & aggAll$Group.2 == "X"] - ((aggAllNot$x)[aggAllNot$Group.1 == "Outcome100" & aggAllNot$Group.2 == "X"])))
emptyPlot(c(-5,105),c(-0.05,0.05), xmark = c(0,50,100), bty='n', main = "Weights allergic minus not", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,-0.02,legend =c("A", "B", "X"), pch = c(0,16,15))


A<- c(0.015888184/(0.015888184+0.017845894	), 0.027604386	/(0.027604386		+0.005708984	), 0.037861935	/(0.037861935	+(-0.004657375)))
B<- c(0.017863459	/(0.017863459	+0.014812799		), 0.008840776	/(0.008840776	+0.023427966		), -0.004592513	/(-0.004592513	+0.036755858))
X<- c(0.033751643	/(0.033751643	+0.032658693	), 0.036445162	/(0.036445162	+0.029136949	), 0.033269422	/(0.033269422	+0.032098483	))
#NOT SURE IF THERE SHOULD BE ABSOLUTES IN HERE SINCE NOW THERE IS THE ISSUE OF GOING HIGHER THAN 1 AND LOWER THAN 0. HOWVEVER WITH ABS IN THERE IT LOOKS MORE STRAIGHT, WHICH ALSO DOES NOT SEEM RIGHT
emptyPlot(c(-5,105),c(0,1), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))

A<- c(0.015888184/(0.015888184+0.017845894	), 0.027604386	/(0.027604386		+0.005708984	), 0.037861935	/(0.037861935	+0))
B<- c(0.017863459	/(0.017863459	+0.014812799		), 0.008840776	/(0.008840776	+0.023427966		), 0	/(0	+0.036755858))
X<- c(0.033751643	/(0.033751643	+0.032658693	), 0.036445162	/(0.036445162	+0.029136949	), 0.033269422	/(0.033269422	+0.032098483	))
#RELU
emptyPlot(c(-5,105),c(0,1), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method, with RELU", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))

```
<br />

### VHW, split groups
```{r}
Group1_1 <- bind_rows(ParticipantRun(Cues2, Cues1, Cues3, Outcome050, Outcome000, Outcome100, 3, etaNeg = TRUE))
Group1_2 <- bind_rows(ParticipantRun(Cues5, Cues6, Cues4, Outcome050, Outcome100, Outcome000, 4, etaNeg = TRUE))
Group1 <- rbind(Group1_1, Group1_2)

Group2_1 <- bind_rows(ParticipantRun(Cues1, Cues3, Cues2, Outcome000, Outcome100, Outcome050, 4, etaNeg = TRUE))
Group2_2 <- bind_rows(ParticipantRun(Cues4, Cues5, Cues6, Outcome000, Outcome050, Outcome100, 4, etaNeg = TRUE))
Group2 <- rbind(Group2_1, Group2_2)

Group3_1 <- bind_rows(ParticipantRun(Cues3, Cues2, Cues1, Outcome100, Outcome050, Outcome000, 3, etaNeg = TRUE))
Group3_2 <- bind_rows(ParticipantRun(Cues6, Cues4, Cues5, Outcome100, Outcome000, Outcome050, 3, etaNeg = TRUE))
Group3 <- rbind(Group3_1, Group3_2)

Group4_1 <- bind_rows(ParticipantRun(Cues5, Cues6, Cues4, Outcome050, Outcome100, Outcome000, 4, etaNeg = TRUE))
Group4_2 <- bind_rows(ParticipantRun(Cues2, Cues1, Cues3, Outcome050, Outcome000, Outcome100, 4, etaNeg = TRUE))
Group4 <- rbind(Group4_1, Group4_2)

Group5_1 <- bind_rows(ParticipantRun(Cues4, Cues5, Cues6, Outcome000, Outcome050, Outcome100, 5, etaNeg = TRUE))
Group5_2 <- bind_rows(ParticipantRun(Cues1, Cues3, Cues2, Outcome000, Outcome100, Outcome050, 5, etaNeg = TRUE))
Group5 <- rbind(Group5_1, Group5_2)

Group6_1 <- bind_rows(ParticipantRun(Cues6, Cues4, Cues5, Outcome100, Outcome000, Outcome050, 4, etaNeg = TRUE))
Group6_2 <- bind_rows(ParticipantRun(Cues3, Cues2, Cues1, Outcome100, Outcome050, Outcome000, 4, etaNeg = TRUE))
Group6 <- rbind(Group6_1, Group6_2)

All2 <- rbind(Group1, Group2, Group3, Group4, Group5, Group6)
All2$wordType <- NA
for(i in 1:nrow(All2)){
  All2[i,]$wordType <- getwords[gsub("...[0-9]+", "",row.names(All[i,]))]
  
}

#So now that we have all, we wanna aggregate over Cond and wordType, to see if we can get the same averages
aggAll2 <- aggregate(All2$Allergic, list(All2$Cond, All2$wordType), mean)
aggAll2
aggAllNot2 <- aggregate(All2$Not, list(All2$Cond, All2$wordType), mean)
aggAllNot2


```


```{r}
par(mfrow = c(1,2))
A <- c((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "A"], (aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "A"], (aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "A"])
B <- c((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "B"], (aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "B"], (aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "B"])
X <- c((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "X"], (aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "X"], (aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "X"])
emptyPlot(c(-5,105),c(-0.05,0.05), xmark = c(0,50,100), bty='n', main = "Weights allergic", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,-0.02,legend =c("A", "B", "X"), pch = c(0,16,15))

A<- c(((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "A"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome000" & aggAllNot2$Group.2 == "A"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "A"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome050" & aggAllNot2$Group.2 == "A"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "A"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome100" & aggAllNot2$Group.2 == "A"])))
B<- c(((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "B"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome000" & aggAllNot2$Group.2 == "B"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "B"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome050" & aggAllNot2$Group.2 == "B"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "B"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome100" & aggAllNot2$Group.2 == "B"])))
X<- c(((aggAll2$x)[aggAll2$Group.1 == "Outcome000" & aggAll2$Group.2 == "X"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome000" & aggAllNot2$Group.2 == "X"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome050" & aggAll2$Group.2 == "X"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome050" & aggAllNot2$Group.2 == "X"])), ((aggAll2$x)[aggAll2$Group.1 == "Outcome100" & aggAll2$Group.2 == "X"] - ((aggAllNot2$x)[aggAllNot2$Group.1 == "Outcome100" & aggAllNot2$Group.2 == "X"])))
emptyPlot(c(-5,105),c(-0.07,0.09), xmark = c(0,50,100), bty='n', main = "Weights allergic minus not", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,-0.02,legend =c("A", "B", "X"), pch = c(0,16,15))


A<- c(-0.001586264/(-0.001586264+0.002950476), 0.018682717/(0.018682717+(-0.017336148)), 0.041685812/(0.041685812+(-0.040343811)))
B<- c(0.010979232/(0.010979232+(-0.003574658)), -0.009350853/(-0.009350853+0.016659667), -0.032363305/(-0.032363305+0.039647324))
X<- c(0.034207713/(0.034207713+0.033326685), 0.036980211/(0.036980211+0.029680798), 0.033639368/(0.033639368+0.032795492))
#NOT SURE IF THERE SHOULD BE ABSOLUTES IN HERE SINCE NOW THERE IS THE ISSUE OF GOING HIGHER THAN 1 AND LOWER THAN 0. HOWVEVER WITH ABS IN THERE IT LOOKS MORE STRAIGHT, WHICH ALSO DOES NOT SEEM RIGHT
emptyPlot(c(-5,105),c(0,1), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))

A<- c(0/(0+0.002950476), 0.018682717/(0.018682717+0), 0.037861935/(0.037861935+0))
B<- c(0.010979232/(0.010979232+0), 0/(0+0.016659667), 0/(0	+0.039647324))
X<- c(0.034207713/(0.034207713+0.033326685), 0.036980211/(0.036980211+0.029680798), 0.033639368/(0.033639368+0.032795492))
#RELU
emptyPlot(c(-5,105),c(0,1), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method, with RELU", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))
```
<br />

### Some extra experimentation
```{r}
A<- c(exp(0.015888184)/(exp(0.015888184)+exp(0.017845894)), exp(0.027604386)/(exp(0.027604386)+exp(0.005708984)), exp(0.037861935)/(exp(0.037861935)	+exp(-0.004657375)))
B<- c(exp(0.017863459)/(exp(0.017863459)+exp(0.014812799)), exp(0.008840776)/(exp(0.008840776)+exp(0.023427966)), exp(-0.004592513)/(exp(-0.004592513)	+exp(0.036755858)))
X<- c(exp(0.033751643)/(exp(0.033751643)+exp(0.032658693)), exp(0.036445162)/(exp(0.036445162)+exp(0.029136949)), exp(0.033269422)/(exp(0.033269422) +exp(0.032098483)))
emptyPlot(c(-5,105),c(0.485,0.515), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))


A<- c(exp(-0.001586264)/(exp(-0.001586264)+exp(0.002950476)), exp(0.018682717)/(exp(0.018682717)+exp(-0.017336148)), exp(0.041685812)/(exp(0.041685812)+exp(-0.040343811)))
B<- c(exp(0.010979232)/(exp(0.010979232)+exp(-0.003574658)), exp(-0.009350853)/(exp(-0.009350853)+exp(0.016659667)), exp(-0.032363305)/(exp(-0.032363305)+exp(0.039647324)))
X<- c(exp(0.034207713)/(exp(0.034207713)+exp(0.033326685)), exp(0.036980211)/(exp(0.036980211)+exp(0.029680798)), exp(0.033639368)/(exp(0.033639368)+exp(0.032795492)))
emptyPlot(c(-5,105),c(0.47,0.53), xmark = c(0,50,100), bty='n', main = "Weights transformed\n with the x/x+y method", xlab = "Condition", ylab = "Probability")
points(c(0, 50, 100),A, pch = 0, type = "b")
points(c(0, 50, 100),B, pch =16, type = "b", lty = 2)
points(c(0, 50, 100),X, pch =15, type = "b", lty = 4)
legend(0.05,0.2,legend =c("A", "B", "X"), pch = c(0,16,15))


```


# BY TRIAL
```{r}
ByTrial_RW <- aggregate(list(All$Allergic, All$Not), list(All$Trial, All$Cond, All$wordType), mean) 
colnames(ByTrial_RW) <- c("TrialNr", "Cond", "FoodGroup", "Allergic", "Not")
#head(ByTrial_RW)
Cond000 <- filter(ByTrial_RW, Cond == "Outcome000")
Cond050 <- filter(ByTrial_RW, Cond == "Outcome050")
Cond100 <- filter(ByTrial_RW, Cond == "Outcome100")


ByTrial_VHW <- aggregate(list(All2$Allergic, All2$Not), list(All2$Trial, All2$Cond, All2$wordType), mean) 
colnames(ByTrial_VHW) <- c("TrialNr", "Cond", "FoodGroup", "Allergic", "Not")
Cond000_2 <- filter(ByTrial_VHW, Cond == "Outcome000")
Cond050_2 <- filter(ByTrial_VHW, Cond == "Outcome050")
Cond100_2 <- filter(ByTrial_VHW, Cond == "Outcome100")

```

```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.01,0.08), xmark = c(1:16), bty='n', main= "Cond000, weights to activation")
points(c(1:16), (Cond000$Allergic)[Cond000$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond000$Allergic)[Cond000$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond000$Allergic)[Cond000$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.06,legend =c("A", "B", "X"), pch = c(0,16,15))



emptyPlot(c(1,16),c(-0.015,0.025), xmark = c(1:16), bty='n', main= "Cond000, weigths activation\n minus not")
points(c(1:16), (Cond000$Allergic - Cond000$Not)[Cond000$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond000$Allergic - Cond000$Not)[Cond000$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond000$Allergic - Cond000$Not)[Cond000$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.025,legend =c("A", "B", "X"), pch = c(0,16,15))
```

```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.01,0.08), xmark = c(1:16), bty='n', main= "Cond050, weights to activation")
points(c(1:16), (Cond050$Allergic)[Cond050$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond050$Allergic)[Cond050$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond050$Allergic)[Cond050$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.06,legend =c("A", "B", "X"), pch = c(0,16,15))


emptyPlot(c(1,16),c(-0.03,0.04), xmark = c(1:16), bty='n', main= "Cond050, weigths activation\n minus not")
points(c(1:16), (Cond050$Allergic - Cond050$Not)[Cond050$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond050$Allergic - Cond050$Not)[Cond050$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond050$Allergic - Cond050$Not)[Cond050$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.04,legend =c("A", "B", "X"), pch = c(0,16,15))
```


```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.01,0.08), xmark = c(1:16), bty='n', main= "Cond100, weights to activation")
points(c(1:16), (Cond100$Allergic)[Cond100$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond100$Allergic)[Cond100$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond100$Allergic)[Cond100$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.06,legend =c("A", "B", "X"), pch = c(0,16,15))



emptyPlot(c(1,16),c(-0.08,0.08), xmark = c(1:16), bty='n', main= "Cond100, weigths activation\n minus not")
points(c(1:16), (Cond100$Allergic - Cond100$Not)[Cond100$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond100$Allergic - Cond100$Not)[Cond100$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond100$Allergic - Cond100$Not)[Cond100$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.08,legend =c("A", "B", "X"), pch = c(0,16,15))
```
```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.02,0.08), xmark = c(1:16), bty='n', main= "Cond000, weights to activation")
points(c(1:16), (Cond000_2$Allergic)[Cond000_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond000_2$Allergic)[Cond000_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond000_2$Allergic)[Cond000_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.06,legend =c("A", "B", "X"), pch = c(0,16,15))



emptyPlot(c(1,16),c(-0.02,0.04), xmark = c(1:16), bty='n', main= "Cond000, weigths activation\n minus not")
points(c(1:16), (Cond000_2$Allergic - Cond000_2$Not)[Cond000_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond000_2$Allergic - Cond000_2$Not)[Cond000_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond000_2$Allergic - Cond000_2$Not)[Cond000_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.04,legend =c("A", "B", "X"), pch = c(0,16,15))
```

```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.04,0.08), xmark = c(1:16), bty='n', main= "Cond050, weights to activation")
points(c(1:16), (Cond050_2$Allergic)[Cond050_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond050_2$Allergic)[Cond050_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond050_2$Allergic)[Cond050_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,0.07,legend =c("A", "B", "X"), pch = c(0,16,15))


emptyPlot(c(1,16),c(-0.08,0.08), xmark = c(1:16), bty='n', main= "Cond050, weigths activation\n minus not")
points(c(1:16), (Cond050_2$Allergic - Cond050_2$Not)[Cond050_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond050_2$Allergic - Cond050_2$Not)[Cond050_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond050_2$Allergic - Cond050_2$Not)[Cond050_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,-0.02,legend =c("A", "B", "X"), pch = c(0,16,15))
```

```{r}
par(mfrow = c(1,2))

emptyPlot(c(1,16),c(-0.07,0.09), xmark = c(1:16), bty='n', main= "Cond100, weights to activation")
points(c(1:16), (Cond100_2$Allergic)[Cond100_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond100_2$Allergic)[Cond100_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond100_2$Allergic)[Cond100_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,-0.03,legend =c("A", "B", "X"), pch = c(0,16,15))



emptyPlot(c(1,16),c(-0.15,0.15), xmark = c(1:16), bty='n', main= "Cond100, weigths activation\n minus not")
points(c(1:16), (Cond100_2$Allergic - Cond100_2$Not)[Cond100_2$FoodGroup == "A"], pch = 0, type = "b")
points(c(1:16), (Cond100_2$Allergic - Cond100_2$Not)[Cond100_2$FoodGroup == "B"], pch = 16, type = "b", lty = 2)
points(c(1:16), (Cond100_2$Allergic - Cond100_2$Not)[Cond100_2$FoodGroup == "X"], pch = 15, type = "b", lty = 4)
legend(1,-0.05,legend =c("A", "B", "X"), pch = c(0,16,15))
```

```{r}
listY <- list()
FirstRun <- data.frame(Cues = Cues2, Outcomes = Outcome050, stringsAsFactors = FALSE)
train.FR <- createTrainingData(FirstRun, random = F)
wm.FR <- EDLearning(train.FR, progress = F, etaNeg = FALSE)
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.FR,i))
  df$Trial <- i
  listX<-list.append(listX, df)
}
#listY<- listX
listY <- bind_rows(listX)

SecondRun <- data.frame(Cues = Cues1, Outcomes = Outcome000, stringsAsFactors = FALSE)
train.SR <- createTrainingData(SecondRun, random = F)
wm.SR <- EDLearning(train.SR, progress = F, etaNeg = FALSE, wm = wm.FR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.SR,i))
  df$Trial <- i+16
  listX<-list.append(listX, df)
}
listZ<- bind_rows(listX)
listY<- rbind(listY, listZ)

ThirdRun <- data.frame(Cues = Cues3, Outcomes = Outcome100, stringsAsFactors = FALSE)
train.TR <- createTrainingData(ThirdRun, random = F)
wm.TR <- EDLearning(train.TR, progress = F, etaNeg = FALSE, wm = wm.SR[[16]])
listX <- list()
for(i in 1:16){
  df <- as.data.frame(getWM(wm.TR,i))
  df$Trial <- i+32
  listX<-list.append(listX, df)
}
listA<- bind_rows(listX)
listY<- rbind(listY, listA)


word <- c("shrimp", "yoghurt", "bananas", "wheat", "corn", "blueberries", "strawberries", "bran", "chicken", "walnuts", "horseradish", "cheese", "peanuts", "cabbage", "mustard", "peaches", "lobster", "pork", "env")
exactWord <- c("shrimp","yoghurt", "bananas", "wheat", "corn", "blueberries", "strawberries", "bran", "chicken", "walnuts", "horseradish", "cheese", "peanuts", "cabbage", "mustard", "peaches", "lobster", "pork", "env")
exactWords <- data.frame(Word = word, exactWord = exactWord, stringsAsFactors = FALSE)
getexactwords <- exactWords$exactWord
names(getexactwords) <- exactWords$Word
listY$Word <- NA
for(i in 1:nrow(listY)){
  listY[i,]$Word <- getexactwords[gsub("...[0-9]+", "",row.names(listY[i,]))]

}

#plotActivations(listY, outcome = "Allergic")

```

```{r}
par(las=1)
emptyPlot(c(1,60),c(-0.03,0.08), xmark = c(1:48), bty='n', main = "Weights to Allergic, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

emptyPlot(c(1,60),c(-0.08,0.09), xmark = c(1:48), bty='n', main = "Weights to Allergic minus not, RW", xlab="trial nr", ylab = "weights")
points(c(1:48), (listY$Allergic)[listY$Word == "bran"]-(listY$Not)[listY$Word=="bran"], type = "l", col = "blue")
points(c(1:48), (listY$Allergic)[listY$Word == "env"]-(listY$Not)[listY$Word=="env"], type = "l", col = "black")
points(c(1:48), (listY$Allergic)[listY$Word == "yoghurt"]-(listY$Not)[listY$Word=="yoghurt"], type = "l", col = "cyan")
points(c(1:48), (listY$Allergic)[listY$Word == "cabbage"]-(listY$Not)[listY$Word=="cabbage"], type = "l", col = "green")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "shrimp"]-(listY$Not)[listY$Word=="shrimp"]), type = "l", col = "pink")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "strawberries"]-(listY$Not)[listY$Word=="strawberries"]), type = "l", col = "red")
points(c(1:48), c(rep(0,16),(listY$Allergic)[listY$Word == "peanuts"]-(listY$Not)[listY$Word=="peanuts"]), type = "l", col = "brown")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "bananas"]-(listY$Not)[listY$Word=="bananas"]), type = "l", col = "yellow")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "chicken"]-(listY$Not)[listY$Word=="chicken"]), type = "l", col = "orange")
points(c(1:48), c(rep(0,32),(listY$Allergic)[listY$Word == "mustard"]-(listY$Not)[listY$Word=="mustard"]), type = "l", col = "grey")
par(xpd=TRUE)
legend(49,0.09,c("bran", "env", "yoghurt", "cabbage", "shrimp", "strawberries", "peanuts", "bananas", "chicken", "mustard"), col = c("blue","black","cyan","green","pink","red","brown","yellow","orange","grey"), lty = c(1,1,1,1,1,1,1,1,1,1))
abline(v=16)
abline(v=32)

```
